### ISSUE TITLE
还有个问题，不能单选吗，直接选中一张图片就直接下一步这样有办法吗

### ISSUE THREAD

**Issue by dary123** [yangpeixing/YImagePicker#11]
还有个问题，不能单选吗，直接选中一张图片就直接下一步这样有办法吗

**Comment by dary123** [comment]
如果直接调用withCrop，点击图片就直接到裁剪了，这样会有个问题，如果是gif的话这边要求不裁剪，直接返回选中的gif地址，如果不是gif才会跳到裁剪，所以想问下有没有单选的方法，在onPickComplete回调里判断图片类型，再决定是否裁剪

**Comment by dary123** [comment]
![image](https://user-images.githubusercontent.com/12826258/67175107-5a5c9780-f3f7-11e9-8325-0826bf07c1c8.png)
好像这个方法没有回调

**Comment by dary123** [comment]
找到方法了，原来是这个  .setSelectMode(SelectMode.MODE_SINGLE)

**Comment by yangpeixing** [comment]
@dary123 问题1：目前微信样式支持单选，只需要maxcount设置为1就行，小红书剪裁不支持单选，问题2：I’mageitem里有个ifGif

**Comment by yangpeixing** [comment]
@dary123 直接点击gif图片，目前没有这个回调，下个版本考虑加入

**Comment by yangpeixing** [comment]
@dary123 回调imageitemclick需要设置setpreview(false)
