### ISSUE TITLE
单单只用裁剪SingleCropActivity.intentCrop，结果回调的裁剪地址感觉没有写全

### ISSUE THREAD

**Issue by dary123** [yangpeixing/YImagePicker#12]
![image](https://user-images.githubusercontent.com/12826258/67185112-b0d9ce00-f417-11e9-8277-a2ff68c8d34f.png)
返回的裁剪后图片地址是/crop_1571643075996.jpg，前面是不是还差点啥

**Comment by yangpeixing** [comment]
@dary123 CropConfig需要指定剪裁图片保存路径，目前新版本2.4.5以后默认添加到根目录crop文件夹内
