### ISSUE TITLE
Android10无法获取到文件

### ISSUE THREAD

**Issue by FynnJason** [yangpeixing/YImagePicker#123]
版本：3.1.4

语言：Kotlin

出现原因：在Android 10以上，选择了图片后，使用File(it.getPath())无法获取到文件

解决办法：在注册清单中申明android:requestLegacyExternalStorage="true"可以获取到文件了

疑问：这是为什么呢？

**Comment by yangpeixing** [comment]
安卓10不允许直接访问非私有目录文件的绝对地址，你需要通过uri去获取到当前文件的路径，并进行加载，android:requestLegacyExternalStorage="true"此代码关闭了安卓10的文件权限管理，所以不受限制

**Comment by HeJingWei** [comment]
在配置清单加了android:requestLegacyExternalStorage="true"这句代码确实不会报权限的错，但是谷歌应用市场发了一个邮箱，说这行代码不允许使用了，请问还有其他解决方法吗
