### ISSUE TITLE
拍照裁剪报错

### ISSUE THREAD

**Issue by shengguan** [yangpeixing/YImagePicker#13]
![image](https://user-images.githubusercontent.com/8409220/67545982-9d877500-f72d-11e9-895a-d15253448b8c.png)

**Comment by yangpeixing** [comment]
@shengguan 请贴出您的使用代码，方便的话+我微  calor0616

**Comment by truesA** [comment]
原因是因为 support demo 清单文件没有加7.0文件配置
`
        <provider
            android:name=".utils.PickerFileProvider"
            android:authorities="${applicationId}.picker.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/picker_file_paths" />
        </provider>`

model 下的清单文件添加这个就好了

**Comment by yangpeixing** [comment]
@shengguan  @truesA  此问题已经在新版本2.4.5中已修复。
