### ISSUE TITLE
请作者尽快适配安卓Q

### ISSUE THREAD

**Issue by JustinChiang123** [yangpeixing/YImagePicker#14]
请作者尽快适配安卓Q

**Comment by yangpeixing** [comment]
@JustinChiang123 目前身边没有安卓10的设备，下个版本我会进行适配，预计11月中旬

**Comment by yangpeixing** [comment]
@JustinChiang123 我刚用模拟器测试过了，所有功能运行正常，不知道您们那边是什么机器出了问题，有没有闪退

**Comment by JustinChiang123** [comment]
> @ JustinChiang123我刚用模拟器测试过了，所有功能运行正常，不知道您们那边是什么机器出了问题，有没有闪退

SdkVersion 29 会出问题，我没在电脑面前现在，好像是sql的问题

**Comment by yangpeixing** [comment]
@JustinChiang123 已适配 SdkVersion 29

**Comment by yangpeixing** [comment]
3.x已全面适配android10
