### ISSUE TITLE
请作者加原图选择的功能

### ISSUE THREAD

**Issue by zhangsange** [yangpeixing/YImagePicker#15]
请作者加类似微信的原图选择的功能。

**Comment by yangpeixing** [comment]
微信的原图功能只是一个标识符，如果点击了原图，则代表按照原图上传，如果没有，需要压缩一下选中图片生成新的图片上传，下个版本会支持原图选择，不过，不会支持原图压缩，需要开发者自己处理压缩代码，下个版本预计11月中旬

**Comment by yangpeixing** [comment]
3.0版本已支持原图选项，但不支持压缩，需要使用者自行处理压缩逻辑
