### ISSUE TITLE
小红书图片选择长图被裁切

### ISSUE THREAD

**Issue by NeVaDaAAA** [yangpeixing/YImagePicker#21]
作者你好,你的这个库非常的棒,更新也很及时.就是我目前发现一个如题目的问题,不知道是因为这是裁剪的逻辑还是bug,希望你能调试一下看看 感谢!

**Comment by yangpeixing** [comment]
小红书图片选择默认就是裁剪的，上面的正方形区域就是裁剪区域。所以当你点击确定的时候，就是裁成正方形的。

**Comment by NeVaDaAAA** [comment]
好的 谢谢

**Comment by yangpeixing** [comment]
@NeVaDaAAA 也支持获取原图，imageItem.path 是原图，imageItem.getCropUrl()是剪裁后的图片

**Comment by yangpeixing** [comment]
@NeVaDaAAA 也支持获取原图，imageItem.path 是原图，imageItem.getCropUrl()是剪裁后的图片

**Comment by NeVaDaAAA** [comment]
能否加一个预览的时候就是原图的开关呢 如果可以的话就太棒了

**Comment by yangpeixing** [comment]
@NeVaDaAAA 不是很明白你的意思，你如果调用小红书剪裁的话，回调里默认就有原图的地址，你预览的时候传入原图地址就好。你如果调用微信选择器的话，默认回调出来的就是原图，预览的也是原图。还是说你想要微信那样有个原图的按钮？

**Comment by NeVaDaAAA** [comment]
明白了 谢谢

**Comment by NeVaDaAAA** [comment]
我目前发现了一个问题 我今天又下了一下你的demo 机型是小米 MIX2S Android 10 系统版本:MIUI 11 9.10.31
发现小红书和微信样式打开以后 全部的图片都不显示。而且没有选择图片，返回也有dialog提示。希望你看下 上周的demo没这个问题 可以加一下我的QQ：511921616

**Comment by NeVaDaAAA** [comment]
我目前发现了一个问题 我今天又下了一下你的demo 机型是小米 MIX2S Android 10 系统版本:MIUI 11 9.10.31
发现小红书和微信样式打开以后 全部的图片都不显示。而且没有选择图片，返回也有dialog提示。希望你看下 上周的demo没这个问题

**Comment by yangpeixing** [comment]
3.0版本已修复
