### ISSUE TITLE
拍照按钮只能点击一次

### ISSUE THREAD

**Issue by ZhanRu** [yangpeixing/YImagePicker#23]
如题，拍照按钮点一次，拍照一次，然后返回相册页面
这时候再点击拍照按钮，是无效的。

版本：com.ypx.yimagepicker:support:2.4.6

**Comment by yangpeixing** [comment]
@ZhanRu 我这边没有复现出来，demo是否也有问题，什么机型？

**Comment by ZhanRu** [comment]
@yangpeixing 平板  我测一下DEMO

**Comment by ZhanRu** [comment]
自己公司的教育平板，MTK6739平台，没有具体型号，自己做的 ..

**Comment by yangpeixing** [comment]
@ZhanRu 加我联系方式 QQ：313930500 微信：calor0616 详聊
