### ISSUE TITLE
Crop文件夹中的图片能不能不要以图片后缀结尾

### ISSUE THREAD

**Issue by dogscar** [yangpeixing/YImagePicker#25]
Crop文件夹中会自动生成很多截略图片，使得一打开本地相册就是这些图片。所以这个文件夹中图片最好不要以图片后缀结尾

**Comment by yangpeixing** [comment]
@dogscar  很好的建议，不过更建议自己指定存储目录，放在应用的私有目录里，这样清除缓存的时候可以删除掉，外部也不能查看到。androidQ以后都是沙盒化存储，外部无法直接查看这些图片

**Comment by yangpeixing** [comment]
3.0版本去除了crop目录，只有DCIM和私有目录
