### ISSUE TITLE
希望能把拍照的点击能自定义

### ISSUE THREAD

**Issue by open9527** [yangpeixing/YImagePicker#27]
预期效果:点击拍照可以弹窗 选择拍照还是拍视频,

实际效果:点击拍照,只能拍照片.

**Comment by yangpeixing** [comment]
@open9527 目前选择器的策略是，当只加载图片时，显示的是拍照，当只加载视频时，显示的是拍摄视频，当加载所有类型时，只显示拍照。你说的弹窗，因为涉及到样式问题，所以需要自定义给使用者实现，目前3.0版本已加入排期，用户可以定制拍照item

**Comment by yangpeixing** [comment]
3.0版本已支持
