### ISSUE TITLE
调用裁剪崩溃

### ISSUE THREAD

**Issue by br3ant** [yangpeixing/YImagePicker#28]
崩溃 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.datedu.pptAssistant/com.ypx.imagepicker.activity.singlecrop.SingleCropActivity}; have you declared this activity in your AndroidManifest.xml?

用法
                        ImagePicker.withMulti(new WXImgPickerPresenter())//指定presenter
                                .mimeType(MimeType.ofImage())
                                .filterMimeType(MimeType.GIF)
                                //设置剪裁比例
                                .setCropRatio(1, 1)
                                .cropSaveFilePath(DirManager.getCropSaveFilePath())
                                //设置剪裁框间距，单位px
                                .cropRectMinMargin(50)
                                //是否圆形剪裁，圆形剪裁时，setCropRatio无效
                                //设置剪裁模式，留白或充满  CropConfig.STYLE_GAP 或 CropConfig.STYLE_FILL
                                .cropStyle(CropConfig.STYLE_FILL)
                                //设置留白模式下生成的图片背景色，支持透明背景
                                .cropGapBackgroundColor(Color.TRANSPARENT)
                                .crop(_mActivity, (OnImagePickCompleteListener) items -> {
                                    //图片剪裁回调，主线程
                                    if (!items.isEmpty()) showIcon(items.get(0).getCropUrl());
                                });

**Comment by yangpeixing** [comment]
support版本上传时，忘记更新manifest，请自行在项目的manifest中添加

        <activity
            android:name=".activity.singlecrop.SingleCropActivity"
            android:multiprocess="true" />

**Comment by yangpeixing** [comment]
@br3ant  support版本在合并时，忘记更新了manifest文件，3.0版本会修复，目前解决方法在自己的app manifest清单中添加
        <activity
            android:name="com.ypx.imagepicker.activity.singlecrop.SingleCropActivity"
            android:multiprocess="true" />

**Comment by yangpeixing** [comment]
@br3ant      <activity
            android:name="com.ypx.imagepicker.activity.singlecrop.SingleCropActivity"
            android:multiprocess="true" />

**Comment by yangpeixing** [comment]
@br3ant support版本在合并时，忘记更新了manifest文件，3.0版本会修复，目前解决方法在自己的app manifest清单中添加
<activity
            android:name="com.ypx.imagepicker.activity.singlecrop.SingleCropActivity"
            android:multiprocess="true" />

**Comment by yangpeixing** [comment]
@br3ant`        <activity
            android:name="com.ypx.imagepicker.activity.singlecrop.SingleCropActivity"
            android:multiprocess="true" />`
