### ISSUE TITLE
裁剪图片的时候主线程卡顿

### ISSUE THREAD

**Issue by Scorption** [yangpeixing/YImagePicker#31]

**Comment by yangpeixing** [comment]
@Scorption 请问是小红书剪裁还是单图剪裁

**Comment by Scorption** [comment]
单图裁剪

**Comment by Scorption** [comment]
微信

**Comment by Scorption** [comment]
@Scorption

**Comment by yangpeixing** [comment]
@Scorption 我这边测试了很多张大图（8000*10000），长图，高清图，没复线出卡顿，方便的话，加我联系方式，具体分析一下。微信：calor0616 或者qq：313930500

**Comment by Scorption** [comment]
@yangpeixing 3.0正式版还没出来吗 出来我再试试

**Comment by yangpeixing** [comment]
3.0版本已经修复了主线程卡顿的问题，请使用者自行实现presenter中showprogressdialog方法，实现一个加载框
