### ISSUE TITLE
apk下载地址失效了

### ISSUE THREAD

**Issue by lindroy** [yangpeixing/YImagePicker#34]
apk下载地址失效了，clone的工程没有成功运行起来，所以希望作者可以重新上传一个apk。

**Comment by yangpeixing** [comment]
@lindroy 坑爹的蒲公英把我账户关闭了，加我联系方式，给你发apk，顺便说一下，下载的项目要选择项目里 androidx目录才行，不能直接用android studio打开我的项目

**Comment by lindroy** [comment]
怎么加哦？你可以直接把apk放在github吧。

**Comment by lindroy** [comment]
另外提个建议，希望下个版本可以设置渐变色标题栏的，这个实在头疼。

**Comment by yangpeixing** [comment]
@lindroy readme里有我联系方式，另外，3.0预览版已经发布了，可以直接clone项目，支持用户自定义标题栏，远程依赖和文档我会在周末更新

**Comment by yangpeixing** [comment]
已更新3.0
