### ISSUE TITLE
大佬 发现一个崩溃的问题

### ISSUE THREAD

**Issue by dingliufan** [yangpeixing/YImagePicker#35]
MediaPreviewActivity 这个没有注册Demo里面 导致不能远程依赖，只能用Moudle依赖改XML文件，在里面注册MediaPreviewActivity ，才不崩溃，还有源码SingleCropActivity这个报红，原因是activity.SingleCrop在这个包下 而不是multi这个包

**Comment by dingliufan** [comment]
就是预览崩溃问题

**Comment by yangpeixing** [comment]
请下载最新源码，3.0版本还未上传远程仓库，还有目前只更新了androidx版本，support版本暂未更新


 
---原始邮件---
发件人: "dingliufan"<notifications@github.com&gt;
发送时间: 2019年12月4日(星期三) 晚上7:13
收件人: "yangpeixing/YImagePicker"<YImagePicker@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [yangpeixing/YImagePicker] 大佬 发现一个崩溃的问题 (#35)



就是预览崩溃问题

**Comment by dingliufan** [comment]
好的 我用的是support版本，我用的本地依赖，远程依赖不能用，已经弄好了， 感谢大佬回复

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"杨培星"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 晚上7:29
收件人:&nbsp;"yangpeixing/YImagePicker"<YImagePicker@noreply.github.com&gt;;
抄送:&nbsp;"山雨欲来风满楼m."<358892638@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yangpeixing/YImagePicker] 大佬 发现一个崩溃的问题 (#35)



请下载最新源码，3.0版本还未上传远程仓库，还有目前只更新了androidx版本，support版本暂未更新 
 
 
   
 ---原始邮件--- 
 发件人: "dingliufan"<notifications@github.com&amp;gt; 
 发送时间: 2019年12月4日(星期三) 晚上7:13 
 收件人: "yangpeixing/YImagePicker"<YImagePicker@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: Re: [yangpeixing/YImagePicker] 大佬 发现一个崩溃的问题 (#35) 
 
 
 
 就是预览崩溃问题

**Comment by HaitianZhuu** [comment]
@yangpeixing 作者大大，3.0大致什么时候会发布？

**Comment by yangpeixing** [comment]
@dingliufan androidx版本已经push了，远程依赖还没上传，预计在本周内

**Comment by yangpeixing** [comment]
3.0版本已经发布
