### ISSUE TITLE
每次打开图片选择isOriginalImage都被初始化为false

### ISSUE THREAD

**Issue by zhangsange** [yangpeixing/YImagePicker#38]
作者你好，每次打开图片选择时，都会在MultiImagePickerFragment的onViewCreated方法中把isOriginalImage初始化为false。
个人认为这个操作不合理，比如用户在预览页面或者图片选择页面修改isOriginalImage为true后，再进入图片选择器，又改成了默认的false。
建议可以把`ImagePicker.isOriginalImage = false;`这句代码删掉，或采用其他更好的方式。希望采纳。

**Comment by yangpeixing** [comment]
@zhangsange 感谢您的反馈，目前原图功能仅仅是一个开关，选择器默认原图功能是关闭的，所以为false，我一开始设计的初衷是，即调用选择器，即回调数据，理论上不存储持久化数据，如果删除`ImagePicker.isOriginalImage = false;`这句代码，在多处调用选择器时，原图状态会发生混乱，所以每次打开选择器，则代表一次新的选择，都会去重置ImagePicker.isOriginalImage=false。使用者在开启了原图功能的情况下只需要根据ImagePicker.isOriginalImage为false时，在图片选择回调完成时去压缩图片即可。
目前想到的更好的方式，是在选择器回调里加入isOriginalImage对象，但是涉及到没有开启原图的使用者，这个字段有些多余，而且不便于后期拓展，也不适用于自定义回调类型，所以只能采取此下下策，还望包涵！至于为什么没有放到imageitem里。是因为原图选项针对的是一组图片，单独塞入到imageitem有悖于此常量理解。如果您有什么更好的方式，不妨提出来，下个版本酌情优化！

**Comment by yangpeixing** [comment]
@zhangsange 你现在的问题可能是多次打开选择器的时候，没有办法判断用户是否是选中了原图，因为用户很有可能直接返回了选择器，而你要做上传操作时，再去拿ImagePicker.isOriginalImage就一直是false。目前建议的解决方式是，在选择器回调中手动使用临时变量记录ImagePicker.isOriginalImage值，等到做上传操作时，使用自己的临时变量，如果要记住原图状态，可在调用选择器时，手动给ImagePicker.isOriginalImage赋值

**Comment by zhangsange** [comment]
@yangpeixing 您好，由于我这边的业务，一个页面里会有多组图片选择，所有组的图片选择完后再统一压缩或原图上传。按您现在的代码逻辑，所有组的isOriginalImage值都是同一个，不满足我们的需求。目前的我的解决方案是自己拼装一个JavaBean，每次获取每组的图片时，把ImagePicker.isOriginalImage的值赋值给JavaBean中对应的变量。这样解决了所有组isOriginalImage值统一的问题。看您代码中`ImagePicker.isOriginalImage = false;
            uiConfig = presenter.getUiConfig(getWeakActivity());
            setStatusBar();
            findView();`把isOriginalImage =false后调用了presenter.getUiConfig方法。所以我在打开选图和预览时，把每组JavaBean中的isOriginalImage值，赋值给WeChatPresenter，再在WeChatPresenter的getUiConfig方法中，把值赋值给ImagePicker.isOriginalImage。这样就解决了每组图片的isOriginalImage值不一样，并在选图或预览是能正确的保存上次选择的状态。这是暂时 的解决方案，希望以后能有更好的。

**Comment by yangpeixing** [comment]
@zhangsange 感谢您提供的使用场景！方便加我联系方式吗？想具体了解一下你们的原图规则，微信：calor0616

**Comment by yangpeixing** [comment]
3.1版本中已经将isOriginalImage移动到imageitem中,每次调用选择器可以设置原图的开关
 .setDefaultOriginal(false)
