### ISSUE TITLE
可以加自定义切图保存路径吗？

### ISSUE THREAD

**Issue by zhangsange** [yangpeixing/YImagePicker#42]
作者你好，可以加自定义切图保存路径吗？

**Comment by yangpeixing** [comment]
@zhangsange 3.0版本默认只能存储到DCIM公共目录 和  android/data/包名/files/私有目录，其中files私有目录中可以指定文件名，具体请查看：(https://github.com/yangpeixing/YImagePicker/wiki/questions#1yimagepicker中拍照和剪裁的图片生成目录在哪里-)
