### ISSUE TITLE
支持一下，希望能增加录视频的最大时间

### ISSUE THREAD

**Issue by Jibinghao** [yangpeixing/YImagePicker#43]
MediaStore.EXTRA_DURATION_LIMIT 这个参数可以配置，我觉得挺多人会用到的，

**Comment by yangpeixing** [comment]
@Jibinghao 👌好的，已加入下个版本排期。。。

**Comment by Jibinghao** [comment]
有个小bug，第一次点击拍摄照片，会去申请权限，这个时候如果我选择的是录像，权限拿到后是拍照而不是录像，代码这里是不是要2个REQUEST_CODE，不然区分不去接下来是取拍照还是录像。
![image](https://user-images.githubusercontent.com/12150259/71349106-1b8abf80-25a9-11ea-8a81-b81ace5652fb.png)

**Comment by yangpeixing** [comment]
@Jibinghao 是bug！感谢反馈！

**Comment by yangpeixing** [comment]
3.1版本添加了视频最大时间限制,[详情查看](https://github.com/yangpeixing/YImagePicker/wiki/Documentation_3.x#拍视频)
若要在选择器中添加视频时长,则直接调用.setMaxVideoDuration(120000L)//设置视频可选取的最大时长 此变量也代表视频可录制的最大时长

权限问题3.1版本忘记添加,实在不好意思,现阶段解决方案是在presenter中拦截掉拍照和拍视频,在调用
takePhoto.takePhoto();之前使用者自行判断好权限
