### ISSUE TITLE
自定义文本（作者回复：3.1版本将会统一选择器所有文案，并且可以定制和修改）

### ISSUE THREAD

**Issue by HaitianZhuu** [yangpeixing/YImagePicker#45]
作者你好，首先感谢维护这么好用的库。PickConstants中只提供了部分常用的文本配置途径，但比如在选择文件夹时，“所有图片”，“张”这样的文字，开发者不能自定义。期望作者把这些也加进去，开发者可以自定义这些文本

**Comment by yangpeixing** [comment]
@HaitianZhuu 感谢您的支持，“所有图片”，“所有视频”
`    <string name="picker_str_piece">张</string>
    <string name="picker_str_all">图片和视频</string>
    <string name="picker_str_all_video">所有视频</string>
    <string name="picker_str_all_image">所有图片</string>
    <string name="picker_str_mimetypes_empty">请至少选择一种文件加载类型!</string>
    <string name="str_single_crop_error">剪裁异常，已为您重置图片，请重试！</string>`
等文案因为涉及到媒体库扫描逻辑，所以暂未开放修改。又因为框架内理论上不允许出现硬编码，string资源需要依赖于context，使用者修改又需要依赖于presenter，单一职责的原理中本不应该在扫描逻辑中处理自定义操作，所以当时出于考虑将这些默认文案锁死，不支持修改，下个版本会考虑方案优化掉，支持所有常量定制！预计下版本在1月初左右，届时会回复这条issue，还请关注！

**Comment by HaitianZhuu** [comment]
好的，谢谢！那我先直接引入library，在代码中改一下

**Comment by yangpeixing** [comment]
@HaitianZhuu 👌

**Comment by HaitianZhuu** [comment]
还有这里：
![image](https://user-images.githubusercontent.com/47531353/71469491-4fadec80-2804-11ea-9982-781dee9cb5d8.png)

**Comment by yangpeixing** [comment]
@HaitianZhuu 好的👌

**Comment by yangpeixing** [comment]
3.1版本已完全去除所有代码中的硬编码,[详情查看](https://github.com/yangpeixing/YImagePicker/wiki/Documentation_3.x#全局常量配置)

**Comment by HaitianZhuu** [comment]
Nice!
