### ISSUE TITLE
微信多选图片时可否加入裁剪功能?

### ISSUE THREAD

**Issue by zhuxu1** [yangpeixing/YImagePicker#47]
微信多选图片时可否加入裁剪功能?

**Comment by yangpeixing** [comment]
@zhuxu1 不好意思，没理解你的需求。。。

**Comment by zhuxu1** [comment]
> @zhuxu1 不好意思，没理解你的需求。。。

微信多选图片 预览模式时的裁剪功能
参考当前微信Android客户端朋友圈选择图片

**Comment by yangpeixing** [comment]
@zhuxu1 你指的是微信图片预览时的编辑功能吧？目前还不支持预览时剪裁图片，不过可以支持自定义预览页面
https://github.com/yangpeixing/YImagePicker/wiki/questions#6如何跳转到自己项目里自定义的预览界面然后返回刷新选择器选择状态

**Comment by yangpeixing** [comment]
3.1版本支持对一组图片进行剪裁,参考demo中alohaActivity
