### ISSUE TITLE
膜拜大佬

### ISSUE THREAD

**Issue by zippo88888888** [yangpeixing/YImagePicker#48]
我也写过一个没有**三方库**的高仿微信的图片选择框架，但是功能没有这么复杂，期间的问题也很多！但是对比这个库，可想而知出现过多少的问题，实在是佩服大佬！三连走起！

**Comment by yangpeixing** [comment]
@zippo88888888 非常感谢您的支持！真正能达到不用三方库去实现一个图片选择的框架其实是很不容易的。这就意味着所有的东西都得重复造轮子。有的人会问，三方库那么成熟，为什么不使用呢？其实我想的很简单，就比如photoview和ucrop两大开源，如果我的框架里整合了这两个框架，首先我维护的成本翻倍，产出的bug也会随着两个库的bug翻倍！所以我设计的初衷就是用一个cropimageview替代两个库，既能实现两个库的大部分功能，又能增强稳定性和维护成本，何乐不为？所以开源不易，更需努力💪
