### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by qiushui95** [yangpeixing/YImagePicker#49]
首先感谢作者的开源。建议将三种方式写成三个扩展库，按需引用，bug修复也方便一些。

**Comment by yangpeixing** [comment]
@qiushui95 感谢您的提议，按照模块划分来说，确实应该把小红书和微信样式拓展成两个库，但是在设计框架的时候，发现小红书和微信样式完全没有什么区别，连adapter都是共通的，剪裁都是统一用的cropimageview，所以分成两个库，不仅大小没有减少，而且维护成本更大，再加上维护support版本的话，就需要维护6个项目了！所以没有拓展的必要性。
不过可以在你的提议上，将媒体数据回调和剪裁可以单独拿出来成立一个新库，目前剪裁的库已经加入排期～
