### ISSUE TITLE
直接裁剪时是否可以加入多图裁剪（作者回复：此属于定制需求，目前已经可以实现单页面剪裁多图，下个版本会放在demo里）

### ISSUE THREAD

**Issue by charmeleon2** [yangpeixing/YImagePicker#50]
现在直接裁剪只能是作用一张图片吧，能不能做一个功能，直接裁剪的页面可以传入多张图片，调整好裁剪框后对所有图片统一裁剪

**Comment by yangpeixing** [comment]
@charmeleon2 目前小红书样式是支持多图剪裁的，如果你想做单页面支持剪裁多图，内置的cropimageview也是支持的。不过我一直没想明白的就是单页面剪裁多图，怎么切换图片和剪裁比例，如果可以的话，加我微信，给我看下你们的效果，如果简单，年前考虑加入框架中！

**Comment by charmeleon2** [comment]
小红书裁剪我看了下似乎不能自定义裁剪比例,这样吧，我加一下您的wx看一下效果

**Comment by yangpeixing** [comment]
@charmeleon2 小红书不能自定义，但是cropimageview支持自定义比例，具体页面需要定制，微信：calor0616

**Comment by yangpeixing** [comment]
3.1demo中已添加alohaactivity来实现多图统一剪裁
