### ISSUE TITLE
华为p20 pro 图片显示问题

### ISSUE THREAD

**Issue by ruhaly** [yangpeixing/YImagePicker#55]
手机：华为p20 pro， 版本 10.0
![image](https://user-images.githubusercontent.com/4638754/72675592-991af000-3ac1-11ea-89fe-38c23396d570.png)
3.+跟2.+都有这个问题，其他手机暂未发现

**Comment by yangpeixing** [comment]
@ruhaly 您好，图片看不了，还麻烦您加我微信calor0616发给我看一下什么问题
