### ISSUE TITLE
AndroidQ手机无法选择图片和拍照

### ISSUE THREAD

**Issue by handsomezwj** [yangpeixing/YImagePicker#58]

**Comment by yangpeixing** [comment]
demo上也无法选择和拍照吗？可否具体提供一下异常截图
如果demo正常，请检查下项目里的manifest是否添加
  android:requestLegacyExternalStorage="true"
代码

**Comment by angcyo** [comment]
```
android:requestLegacyExternalStorage="true"
```

这种行为不可取, 建议尽快兼容`AndroidQ`文件沙箱模式.

**Comment by yangpeixing** [comment]
@angcyo 如果你的targetsdk和compileSdkVersion都设置了大于29,理论上加载图片时不能使用path绝对路径,但是考虑到目前没有升级的人较多,绝对路径使用的人也较多,所以demo做了兼融处理.如果您不加上面的配置,则需要在presenter的displayimage方法中使用uri加载
`    @Override
    public void displayImage(View view, ImageItem item, int size, boolean isThumbnail) {
        if (item.getId() > 0 && item.getUri() != null) {
            Glide.with(view.getContext()).load(item.getUri()).apply(new RequestOptions()
                    .format(isThumbnail ? DecodeFormat.PREFER_RGB_565 : DecodeFormat.PREFER_ARGB_8888))
                    .into((ImageView) view);
        } else {
            Glide.with(view.getContext()).load(item.path).apply(new RequestOptions()
                    .format(isThumbnail ? DecodeFormat.PREFER_RGB_565 : DecodeFormat.PREFER_ARGB_8888))
                    .into((ImageView) view);
        }
    }`

**Comment by yangpeixing** [comment]
`
     @Override
    public void displayImage(View view, ImageItem item, int size, boolean isThumbnail) {
        if (item.getId() > 0 && item.getUri() != null) {
            Glide.with(view.getContext()).load(item.getUri()).apply(new RequestOptions()
                    .format(isThumbnail ? DecodeFormat.PREFER_RGB_565 : DecodeFormat.PREFER_ARGB_8888))
                    .into((ImageView) view);
        } else {
            Glide.with(view.getContext()).load(item.path).apply(new RequestOptions()
                    .format(isThumbnail ? DecodeFormat.PREFER_RGB_565 : DecodeFormat.PREFER_ARGB_8888))
                    .into((ImageView) view);
        }
    }
`

**Comment by yangpeixing** [comment]
3.1版本已经去除掉兼容android:requestLegacyExternalStorage="true"代码,已完全适配选择器
