### ISSUE TITLE
相机界面能否自定义

### ISSUE THREAD

**Issue by charmeleon2** [yangpeixing/YImagePicker#61]
我看有个拦截拍照按钮的接口，但是其中ICameraExecutor似乎无法设置，默认实现是在PBaseLoaderFragment类中，外部无法干预？

**Comment by yangpeixing** [comment]
@charmeleon2 相机拍照的item可以定制,但是拍照的页面目前demo调用的是系统的拍照页面,无法做定制, 如果你需要跳转到自己项目的拍照页面,则直接跳转就好,在拍照回调后调用ICameraExecutor.onTakePhotoResult 刷新选择器即可
