### ISSUE TITLE
videoImageUri 没有set方法 

### ISSUE THREAD

**Issue by hyhyhykw** [yangpeixing/YImagePicker#65]
videoImageUri 没有set方法,缩略图如果直接设置到path上 就没办法同时获取视频路径和缩略图路径

**Comment by yangpeixing** [comment]
@hyhyhykw 感谢反馈,可能误删了,实在不好意思,下个版本我加上

**Comment by yangpeixing** [comment]
@hyhyhykw 3.1.1班额本已经添加
