### ISSUE TITLE
微信保存的图片，在安卓10上无法检索到。

### ISSUE THREAD

**Issue by jqorz** [yangpeixing/YImagePicker#66]
小米9，安卓10的机器，微信保存的图片，检索不到，Demo里也检索不到。Tencent/MicroMsg/WeiXin文件夹中有11张照片，使用Demo进行测试，只能显示9张，最近保存的都无法显示。但是其他系统应用以及微信微博都可以检索到11张图片

**Comment by yangpeixing** [comment]
@jqorz 非常感谢您的反馈,微信保存的图片确实会有问题,目前已定位到问题所在,微信在保存图片时并没有指定图片的mimetype,导致微信保存的图片在媒体数据库中是空,但是框架通过mimetype检索,只加载对应的13种mimetype格式文件,所以,会遗漏掉没有指定的mimetype图片,目前这个问题正在急速解决,预计这两天会在3.1.2版本中修复

**Comment by yangpeixing** [comment]
@jqorz 非常感谢您的反馈,经过确认确实存在这个问题,目前已跟踪到问题所在是因为框架内未处理  image/jpg  类型的mimetype,此 bug将在3.1.2版本中修复,预计发布时间 3月12日之前

**Comment by yangpeixing** [comment]
@jqorz 3.1.2版本已发布,已修复此问题
