### ISSUE TITLE
权限申请完之后没有立即打开相机

### ISSUE THREAD

**Issue by xuhang96** [yangpeixing/YImagePicker#68]
权限申请完之后没有立即打开相机

**Comment by yangpeixing** [comment]
@xuhang96 框架内部调用摄像头是支持打开权限立即调用，而takephoto不支持是因为权限回调需要调用方activity的onpression回调。框架无法处理，所以在调用takephoto方法之前请自行在调用的activity处理权限回调逻辑

**Comment by xuhang96** [comment]
好的
