### ISSUE TITLE
同事的手机会显示黑色占位图，并且不能选择，选了之后是拿不到文件的。

### ISSUE THREAD

**Issue by wpsmgkn** [yangpeixing/YImagePicker#69]
同事的手机会显示黑色占位图，好像是 图片路径有，但是没图片。并且不能选择，选了之后是拿不到文件的。不知道什么情况

**Comment by yangpeixing** [comment]
@wpsmgkn 加我微信calor0616联调一下

**Comment by abcdisgreat** [comment]
@yangpeixing 使用demo在华为Android10的机子上也发现了这种现象，相册数据较多一千条以上，使用微信样式进入在滑到三四百条的时候开始显示黑色占位，选择自定义样式进入之间第一页开始就是占位图了

**Comment by yangpeixing** [comment]
@wpsmgkn 加我微信联调一下。。。。

**Comment by yangpeixing** [comment]
@wpsmgkn 问题产生原因是在某些（p30）机器上使用Glide加载content uri路径会卡死导致显示不出图片。解决方式为升级Glide至4.11.0版本即可解决

 implementation 'com.github.bumptech.glide:glide:4.11.0'

**Comment by yangpeixing** [comment]
@abcdisgreat

**Comment by abcdisgreat** [comment]
@yangpeixing 升级了demo的glide还是会出现
![FjSzfMuxjVYAE-l_IMQX0uWsvoKb](https://user-images.githubusercontent.com/33865977/78230461-eecd3900-7503-11ea-945d-76cdd4dd941f.jpg)

**Comment by abcdisgreat** [comment]
@yangpeixing 因为最近也在搞AndroidQ得适配，这里我是把targetSdkVersion设置为 29进行测试的

**Comment by yangpeixing** [comment]
@abcdisgreat 方便的话加我联系方式，我们一起看下这个问题，我这边的P30升级了Gilde之后所有的图片都能正常加载。如果不方便的话，解决方式为：改用path加载并在manifest中配置
android:requestLegacyExternalStorage="true"
此方案为稳定替代方案，我会一直跟踪这个问题

**Comment by abcdisgreat** [comment]
@yangpeixing 哈哈，暂时没使用您的库，只是demo打包使用了一下，测试用的同事的华为机子。没有其他品牌Android10不好对比，但我这边用同事p20机子测得自定义样式比微信样式更严重，手机里大概三百张左右进微信样式是能全加载出来的，另一个手机一千多张的就会出现图里的情况。

**Comment by yangpeixing** [comment]
@abcdisgreat 你是什么机型？我这边测试了p30(5000张)，p30pro(15000张),都是正常的😹我心好累~

**Comment by yangpeixing** [comment]
@abcdisgreat p20 安卓10 4000张照片也没有问题

**Comment by abcdisgreat** [comment]
@yangpeixing 那就奇怪了，我下的代码就改了gradle里的版本到29，
然后打的release包安装看效果的。看看后续有没有其他人反馈这种情况吧
