### ISSUE TITLE
小红书图片+视频列表中 如果有视频错误 出现弹窗无法播放此视频，点击确定无限弹出，返回无法取消。

### ISSUE THREAD

**Issue by truesA** [yangpeixing/YImagePicker#7]
机型
小米mix2
系统
8.0
bug
小红书图片+视频列表中 如果有视频错误（ 可能是视频文件删除残留，找不到该视频内容，文件格式存在） 出现弹窗无法播放此视频，点击确定无限弹出，返回无法取消。

**Comment by truesA** [comment]
bug
小红书图片+视频列表中 如果有视频错误（ 可能是视频文件删除残留，找不到该视频内容，文件格式存在） 出现弹窗无法播放此视频，点击确定无限弹出，返回无法取消。
描述
该问题复现解决办法为 视频文件残留导致系统videoView检测出来的报错弹窗。
fix
可以去判断获取视频时长，小于1秒或者获取视频时间为null时的视频不加入视频源

**Comment by yangpeixing** [comment]
感谢您的反馈，确实会有这个问题，造成原因是系统的videoView播放时报错导致弹窗，您的解决方案可行，2.4.3版本会添加判断。预计15号左右push，十分感谢！

**Comment by yangpeixing** [comment]
2.4.3版本已fix
