### ISSUE TITLE
 全部视频文件夹预览图加载问题

### ISSUE THREAD

**Issue by abcdisgreat** [yangpeixing/YImagePicker#72]
allVideoSet.coverPath = allVideoItems.get(0).path;  
displayCoverImage(String coverUrl, IPickerPresenter presenter) 
在Android10上只传路径加载不了图库视频,需要多加个uripath吧

**Comment by yangpeixing** [comment]
@abcdisgreat 感谢反馈，下个版本已经修复，预计发布时间为本周内

**Comment by abcdisgreat** [comment]
@yangpeixing 还有个小问题，ImageItem为什么没有文件名字段，读取相册时能不能把文件名称也放到ImageItem里

**Comment by yangpeixing** [comment]
@abcdisgreat 3.1.3版本已经提交，已经修复了视频问题还有新增了displayName字段
