### ISSUE TITLE
裁剪的问题

### ISSUE THREAD

**Issue by sj8521123** [yangpeixing/YImagePicker#75]
我们产品要求的裁剪页面是这样的，一个界面中会用到多次裁剪、点击确认裁剪、会选择下一张图。但是每次都是第一张显示出裁剪框的样式，剩下的都没有裁剪框的样式、但是裁剪功能还是有的，

![IMG_3764](https://user-images.githubusercontent.com/19721732/79061579-34d48a80-7cc4-11ea-80a8-6f0cb3b67289.JPG)
![IMG_3766](https://user-images.githubusercontent.com/19721732/79061748-c42e6d80-7cc5-11ea-88df-2dfdcd82837e.JPG)
![IMG_3765](https://user-images.githubusercontent.com/19721732/79061750-cb557b80-7cc5-11ea-9db1-44d6d83d6a54.JPG)

**Comment by sj8521123** [comment]
有没有啥办法，让CropImageView 显示出裁剪框的样式

**Comment by yangpeixing** [comment]
@sj8521123 看了下代码，不显示剪裁框是因为cropImageview中如果是圆形剪裁或者镂空剪裁的话话，剪裁的是view，剪裁完毕后把isShowCropRect致为false了，所以下一个剪裁图片剪裁框不显示。解决方案就是引用源码，在cropImageView中添加
`
    public void setShowCropRect(boolean showCropRect) {
        isShowCropRect = showCropRect;
        invalidate();
    }
`
在你需要剪裁下一张图片时调用这个方法

**Comment by yangpeixing** [comment]
@sj8521123 如果不想引用源码，使用反射也是可以的
`

try {
            Field field = CropImageView.class.getDeclaredField("isShowCropRect");
            field.setAccessible(true);
            field.set(mCropImg, true);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }

`

**Comment by sj8521123** [comment]
刚验证了下， 确实是这个原因导致的，感谢您的解答。

**Comment by yangpeixing** [comment]
@sj8521123 感谢您对本框架的支持🌹如果觉得不错还请留个star~
