### ISSUE TITLE
下载3.1.3测试包到手机，选择不加载MOV格式，发现还是被加载出来了。

### ISSUE THREAD

**Issue by Jibinghao** [yangpeixing/YImagePicker#76]
[test.mov.zip](https://github.com/yangpeixing/YImagePicker/files/4468815/test.mov.zip)

这个是mov视频例子

**Comment by Jibinghao** [comment]
测试机器 华为mate20

**Comment by yangpeixing** [comment]
@Jibinghao 3.1.4版本已修复
