### ISSUE TITLE
最新版本使用getPath获取选择后的图片并上传七牛服务器报file or data size is zero

### ISSUE THREAD

**Issue by myAllDream** [yangpeixing/YImagePicker#77]
最新版本使用getPath获取选择后的图片并上传七牛服务器报file or data size is zero，而3.0.1版本不会，使用getPath可以正常把图片上传到七牛服务器，请问这个是什么原因，最新版本的getPath是不是获取原图的path？

**Comment by yangpeixing** [comment]
@myAllDream 3.1.3版本的getPath取得是content路径而不是绝对路径,3.1.4版本已经修复

**Comment by myAllDream** [comment]
@yangpeixing 谢谢作者，更新到3.1.4已经解决，大赞作者

**Comment by yangpeixing** [comment]
@myAllDream 感谢您对本框架的支持🌹，觉得不错还请留个star鼓励一下🌹
