### ISSUE TITLE
有个问题，可以自定义图片资源，用该选择器来展示吗？

### ISSUE THREAD

**Issue by linyouzhen124** [yangpeixing/YImagePicker#78]
感谢作者开源了这个库！
有个问题，可以自定义图片资源，用该选择器来展示吗？

**Comment by yangpeixing** [comment]
@linyouzhen124 这目前是无法支持的，因为自定义图片资源的话，很多信息是无法保证的，比如文件夹信息，图片mimetype，宽高，uri路径还是其他路径等等信息，而这些信息在框架里都有严格的把控和回调，如果暴露图片资源的话，框架可能会出问题，除非自定义图片资源是ImageItem类型。您可以按照目前我框架的逻辑在PBaseLoaderFragment的204行指定文件夹列表，227行指定图片资源。不知道我的回答对你有没有什么帮助，再次感谢您对框架的支持🌹

**Comment by linyouzhen124** [comment]
明白了。非常感谢您的解答。
再次感谢作者的贡献
