### ISSUE TITLE
选择剪裁过的图片再次剪裁时会出问题

### ISSUE THREAD

**Issue by wzx12138** [yangpeixing/YImagePicker#79]
报这个错
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.ypx.imagepicker.bean.selectconfig.MultiSelectConfig)
是哪个值传错了么

**Comment by yangpeixing** [comment]
@wzx12138 加我微信 calor0616我们一起看下

**Comment by zhuxu1** [comment]
最近我也有监控到这个bug，但目前还没复现问题，错误内容一致。如果有解决方案烦请告知
