### ISSUE TITLE
刚看到一个无耻之徒。

### ISSUE THREAD

**Issue by yanjiaxue** [yangpeixing/YImagePicker#83]
https://github.com/XiaoKeXin09/YPX_ImagePicker_support，直接盗取你全部的东西

**Comment by yanjiaxue** [comment]
https://github.com/XiaoKeXin09/YPX_ImagePicker_support

**Comment by yangpeixing** [comment]
感谢您的反馈和提醒！我已经联系该用户进行开源申明！再次感谢您对本框架的支持！！🌹

**Comment by yanjiaxue** [comment]
> 感谢您的反馈和提醒！我已经联系该用户进行开源申明！再次感谢您对本框架的支持！！

客气了
