### ISSUE TITLE
支持拖拽裁剪吗

### ISSUE THREAD

**Issue by shapolang** [yangpeixing/YImagePicker#84]
![1588926849(1)](https://user-images.githubusercontent.com/6863794/81387751-c9a69880-9149-11ea-80fa-41d15c3585c5.png)
这种

**Comment by yangpeixing** [comment]
@shapolang 图片看不到，你加我微信  calor0616

**Comment by AlienChao** [comment]
裁剪边框支持拖拽吗

**Comment by shapolang** [comment]
自动回复
O(∩_∩)O~，亲，邮件已经收到，
