### ISSUE TITLE
如何像微信表情裁剪那样，背景可以镂空，首先要把图片全部显示出来，长方形图也要全部显示，其余部分可以设置背景为白色或者黑色，甚至透明也可以

### ISSUE THREAD

**Issue by dary123** [yangpeixing/YImagePicker#9]
如何像微信表情裁剪那样，背景可以镂空，首先要把图片全部显示出来，长方形图也要全部显示，其余部分可以设置背景为白色或者黑色，甚至透明也可以

**Comment by dary123** [comment]
作者大大，有办法实现吗，对裁剪这块没深入研究过，但是这个需求是产品提的，要求跟微信IOS版，飞聊表情裁剪那样，背景为黑或白或镂空，微信安卓版头像裁剪貌似也是这样，你可以试下，无论缩小到什么地步都不会图片自动回归原位，其余地方背景变成黑色了，或者镂空透明也可以，主要就是想要让长方形图完整显示，但是实际尺寸要求1:1正方形

**Comment by yangpeixing** [comment]
@dary123 框架目前还不支持，下个版本加入，预计11月之前

**Comment by dary123** [comment]
恩恩，感谢，刚好产品给我们的期限就是截止到11月份，希望作者大大可以实现这个功能，回头发红包给你

**Comment by yangpeixing** [comment]
2.4.5版本已经加入
