### ISSUE TITLE
使用前置摄像头拍照裁剪，裁剪时图片加载不出来

### ISSUE THREAD

**Issue by anjiuzhe** [yangpeixing/YImagePicker#95]
机型：华为Nova4e      系统：Android 10
奇怪的问题是使用后置摄像头拍摄可以加载出来，前置摄像头不行。

**Comment by yonghuanjun** [comment]
同样遇到了，已提过 在你自己的Presenter  里面的displayImage 注释掉这行 .override(isThumbnail ? size : Target.SIZE_ORIGINAL)试试

**Comment by yonghuanjun** [comment]
成功了回复我一下，我这个手机是成功了的

**Comment by anjiuzhe** [comment]
OK，可以了，谢谢你 @yangpeixing
