### ISSUE TITLE
请问 如何在拍摄完成后跳转到视频列表页 而不是关闭选择器呢

### ISSUE THREAD

**Issue by hanyulang** [yangpeixing/YImagePicker#98]

**Comment by yangpeixing** [comment]
@hanyulang 可以在presenter中拦截拍照点击

**Comment by hanyulang** [comment]
作者你好，拍摄完成后如何获取视频封面图片文件呢，拍摄完成后 imageitem 的id 为 0

**Comment by yangpeixing** [comment]
@hanyulang 有些手机拍完视频并不会立马生成缩略图存在数据库里，这里我建议你用Glide获取到视频的首图第一帧，然后自己手动保存在一个文件夹中使用。

**Comment by hanyulang** [comment]
好的
